import api from '@config/api';
import { app } from '@shared/infra/http/app';

const apiConfig = api();

app.listen(apiConfig.API_PORT, async () => {
  console.log(`SERVER STARTED ON http://localhost:${apiConfig.API_PORT}`);
});

/** TODO
 *   CRIAR O .ENV E COLOCAR AS INFORMAÇÕES DO BANCO NELE
 *   REFAZER MODELO CONCEITUAL
 *   TALVEZ ADICIONAR CATEGORIAS PARA OS CONTRATOS
 *   PEGAR O EMPLOYER DIRETO NO CONTROLLER POR MEIO DO TOKEN
 *   O MESMO SE REPLICARÁ PARA OS SERVIÇOS EM QUE ADICIONAREMOS UM EMPLOYEE
 *   SE SOBRAR TEMPO:
 *   - INTEGRAR O SERVIÇO DA IBM PARA O UPLOAD DE IMAGENS + O IBM FACADE
 *   - ADICIONAR A ROTA DE DELETE NORMAL
 **/
